version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "willtho89"
    labels:
      - "dependencies"
      - "python"
    groups:
      development:
        patterns:
          - "pytest*"
          - "black"
          - "flake8*"
          - "mypy"
          - "isort"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "willtho89"
    labels:
      - "dependencies"
      - "ci/cd"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "willtho89"
    labels:
      - "dependencies"
      - "docker"